version: '3.8'

services:
  postgres1:
    container_name: pg1
    hostname: postgres1
    image: postgres:16.1-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pg_db
    networks:
      pg-replicated:


  postgres2:
    container_name: pg2
    hostname: postgres2
    image: postgres:17.1-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pg_db
    networks:
      pg-replicated:

networks:  
  pg-replicated:      
    name: pg-replicated